# Generated by Django 5.0 on 2024-01-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0003_blogpost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='likes',
        ),
    ]
