# Generated by Django 5.0 on 2024-01-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artapp', '0007_remove_blogpost_likes_remove_like_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('painting', 'Painting'), ('drawing', 'Drawing'), ('digital_art', 'Digital Art'), ('sculptures', 'Sculptures'), ('pottery', 'Pottery'), ('textile_art', 'Textile Art'), ('jewellery_crafting', 'Jewellery Crafting'), ('fashion_designing', 'Fashion Designing'), ('others', 'Others')], default='others', max_length=20),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
